language: python

matrix:
  include:

    # Here you can add or remove specific builds, and Python versions. You
    # should currently be able to use Python 2.6, 2.7, or 3.3 or later. The
    # NUMPY and SCIPY versions are set here as an example, but you can
    # add/remove environment variables, and use them below during the install.

    - python: 3.6

services:
  - mysql
  - postgresql

addons:
  postgresql: "9.6"

env:
  - CODECOV_TOKEN="50dd5c2e-4259-4cfa-97a7-b4429e0d179e"

before_install:

  # Increase size of database drive
  - sudo mount -o remount,size=50% /var/ramfs

  # Set up the databases - install seqrepo and UTA
  - mysql -e 'CREATE DATABASE validator;'
  - df -h

  - mkdir "$HOME"/seqrepo
  - rsync -HavP dl.biocommons.org::seqrepo/2018-08-21/ "$HOME"/seqrepo/2018-08-21/

  # Copy configuration file
  - cp configuration/travis.ini "$HOME"/.variantvalidator

  # Get validator database
  - wget --output-document=validator_2019-09-18.sql.gz https://leicester.figshare.com/ndownloader/files/21717135
  - gunzip validator_2019-09-18.sql.gz


install:

  # Test dependencies
  - pip install -r requirements_dev.txt
  - pip install -e .

  # Set up validator database
  - mysql validator < validator_2019-09-18.sql

  #  - update_vdb.py
  - df -h

script:

  - pytest --cov-report=term --cov=VariantValidator/ # will run all tests in the package

after_script:
  - codecov